int gcd();
int cipher();
int add_cipher();
int mul_cipher();
int affine_cipher();
int randum();
int auto_cipher();
int sorting();
int search();
int vigenere_cipher();
int rbs();
int ibs();
int ls();
int bsort();
int ssort();
int isort();
int q_sort();
int msort();
int qs(int [],int , int );
int partition(int [], int , int);
int ms(int[] ,int ,int ,int);
int gate();
int OR();
int AND();
int NAND();
int NOR();
int hill_cipher();

